services:
  postgres:
    image: postgres:16-alpine
    container_name: taskflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    ports:
      - "5432:5432"
    volumes:
      - taskflow_pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: taskflow-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  taskflow_pg_data:
